syntax enable
set t_Co=256

filetype plugin indent on
filetype plugin on

" set guifont=Menlo:h14\ Regular
" set guifont=Meslo\ LG\ L\ DZ\ Regular\ for\ Powerline:h14\ Regular
set guifont=Roboto\ Mono\ Medium\ for\ Powerline:h14\ Regular
set number
set cursorline
set lazyredraw
set showmatch
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set foldmethod=indent
set foldlevel=100
set noswapfile
set incsearch
set hlsearch
set eb
set vb
set wrap
set linebreak
set textwidth=0
set wrapmargin=0
set mouse=a
set colorcolumn=80
set wildmenu
set wildmode=list:longest
set wildignore+=*/tmp/*,*.so,*.swp,*.zip
set list
set listchars=trail:.,extends:#,nbsp:.,tab:\ \ 

let g:acp_enableAtStartup = 1
let g:neocomplete#enable_at_startup = 1


autocmd Filetype * match Error /\s\+$/

let g:autotagExcludeSuffixes="tml.xml.text.txt.vim.swp.swo"
let mapleader=","
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

execute pathogen#infect()

colorscheme badwolf
